### ISSUE TITLE
simple example

### ISSUE THREAD

**Issue by kimasendorf** [Korilakkuma/XSound.js#1]
it would be nice to have a simple example of how to make a minimum setup. or i just can't find?

**Comment by Korilakkuma** [comment]
`X('oscillator').setup(true).ready().start(440);  // 440 Hz`

Please paste this code to console of developer tools in Chrome, Opera, Firefox, Safari
on [the site](https://korilakkuma.github.io/X-Sound/) loading this library.

This code is equivalent to the following code.

```javascript
const audiocontext = new AudioContext();
const oscillator   = audiocontext.createOscillator();

oscillator.connect(audiocontext.destination);

oscillator.frequency.value = 440;

oscillator.start(0);
```

For further details, please refer to [API Document](https://korilakkuma.github.io/XSound/).

Thanks.

**Comment by kimasendorf** [comment]
How do you connect the effect modules?

**Comment by kimasendorf** [comment]
ok found it:

```
X('audio').module('autopanner').state(true);
```

thanks for your time.

I still think a simple example would help a lot =)

Best
K

**Comment by kimasendorf** [comment]
When I want to use multiple modules, I just do:

```
X('audio').module('autopanner').state(true);
X('audio').module('chorus').state(true);
```

?

**Comment by Korilakkuma** [comment]
That is exactly right. And, please set parameters.
For example,

```javascript
X('oscillator').setup(true);

// Auto Panner
X('oscillator').module('autopanner').state(true).param({
    depth : 1,
    rate  : 0.5
});

// Chorus
X('oscillator').module('chorus').state(true).param({
    time   : 0.03,
    depth  : 0.5,
    rate   : 0.5,
    mix    : 0.4,
    tone   : 8000
});

X('oscillator').start(440);
```

Thanks.

**Comment by kimasendorf** [comment]
thank you very much! One last thing, how to add a second oscillator?

**Comment by Korilakkuma** [comment]
If you want to create chord, the array of oscillator's state designates to "setup" method.
For example,

```javascript
const base = 40;

X('oscillator').setup([true, true, true]);  // the array of oscillator's state

// C major
// X.toFrequencies (https://korilakkuma.github.io/XSound/#xsound-to-frequencies)
X('oscillator').start(X.toFrequencies([base, (base + 4), (base + 7)]));
```

If yout want to some X('oscillator'), it is required to clone "X" object.

```javascript
const C = X.clone();

C('oscillator').setup(true).ready().start(440);
```

Thanks.

**Comment by kimasendorf** [comment]
thanks again!
